apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespaces
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          env: dev
  - clusters:
      selector:
        matchLabels:
          env: prod
  template:
    metadata:
      name: namespace-{{name}}
    spec:
      project: platform
      source:
        repoURL: https://github.com/baachi8/gitops-argocd-hub-spoke.git
        targetRevision: main
        path: platform/namespaces/nginx
      destination:
        server: '{{server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
